spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_portal?useSSL=false&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: c2619zz
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
com:
  skuniv:
    cs:
      geonyeong:
        crypt:
          key: 123456789789456123456
        jwt:
          secretKey : ThisIsGeonyeongKimWithLyangHwaSpringPortalProjectJwtSecretKey
server:
  port: 9090